"""add Order and OrderItem model

Revision ID: c99658dadffa
Revises: dadd661ba7f5
Create Date: 2026-04-02 21:25:50.074803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c99658dadffa"
down_revision: Union[str, Sequence[str], None] = "dadd661ba7f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "user_id", sa.Integer(), nullable=False, comment="ID пользователя"
        ),
        sa.Column(
            "status",
            sa.Enum("CREATED", "CONFIRMED", "DECLINED", name="orderstatus"),
            nullable=False,
            comment="Статус заказа",
        ),
        sa.Column(
            "total_quantity",
            sa.Integer(),
            nullable=False,
            comment="Общее количество",
        ),
        sa.Column(
            "total_price", sa.Integer(), nullable=False, comment="Общая цена"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "order_id", sa.Integer(), nullable=True, comment="ID заказа"
        ),
        sa.Column("stock_id", sa.Integer(), nullable=True, comment="ID стока"),
        sa.Column(
            "quantity", sa.Integer(), nullable=False, comment="Количество"
        ),
        sa.Column("price", sa.Integer(), nullable=False, comment="Цена"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["item_stocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_items")
    op.drop_table("orders")
    # ### end Alembic commands ###
