"""add ItemStock model

Revision ID: dadd661ba7f5
Revises: b70322ec126b
Create Date: 2026-04-02 21:24:10.677042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadd661ba7f5'
down_revision: Union[str, Sequence[str], None] = 'b70322ec126b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True, comment='ID товара'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Цена'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество'),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False, comment='Зарезервированное количество'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_stocks')
    # ### end Alembic commands ###
